DROP TABLE IF EXISTS `[DBNAME]`.`Type`;
DROP TABLE IF EXISTS `[DBNAME]`.`Notes`;
DROP TABLE IF EXISTS `[DBNAME]`.`NotesMeta`;
DROP TABLE IF EXISTS `[DBNAME]`.`Meta`;
DROP TABLE IF EXISTS `[DBNAME]`.`SysParm`;
